### ISSUE TITLE
Use AnsiColor.DEFAULT instead of AnsiColor.BLACK at the end of banner.txt

### ISSUE THREAD

**Issue by JacksonBailey** [toedter/chatty#5]
The `banner.txt` is a nice example for how to make colored banners, but at the end [[here](https://github.com/toedter/chatty/blob/master/subprojects/com.toedter.chatty.server.boot/src/main/resources/banner.txt#L7)] I think it should use `${AnsiColor.DEFAULT}` instead of `${AnsiColor.BLACK}`.

Yes, 99% of the time Black is the default color (or at least close to black) but not always. Most terminals allow setting a different default color than the other colors and that default color may be white, or pink, or anything.

The only reason I am even bringing it up is because [this](http://toedter.com/2015/12/13/creating-colorful-banners-for-spring-boot-applications/) blog post is the first result when Googling "Spring Boot colored banner" (which points to this file) so this is sort of like a reference in a way.

**Edit:** Actually, `${AnsiStyle.NORMAL}` may be even better. I believe it does `[0m` which I think resets everything (bold, italic, background, foreground, etc.).

**Comment by toedter** [comment]
Thx, changed it to ${AnsiStyle.NORMAL}
